### ISSUE TITLE
Only the files/folders in the "master" branch is copied over.

### ISSUE THREAD

**Issue by starikcetin** [Paraboly/pwc-web-component-template#2]
The orphan branch "repository-resources" doesn't get carried over to the generated repo.
We need to revert to a simpler "assets" folder approach.

**Comment by starikcetin** [comment]
fixed with:

https://github.com/Paraboly/pwc-web-component-template/commit/e8cce64601583bed0d3b5d82a0f81c3eb4630f1e

and

https://github.com/Paraboly/pwc-web-component-template/commit/d1fdae79ad656d888fa81d88cd90c296e01bbe0b

**Comment by WrathChaos** [comment]
the **assets** folder is still available on the master branch @starikcetin

**Comment by starikcetin** [comment]
> the **assets** folder is still available on the master branch @starikcetin

That was the intention. Only the master branch is copied, so they need to be in master branch.
